name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update application on EC2
        env:
          DB_INFO: ${{ secrets.DB_INFO }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PSWD: ${{ secrets.DB_PSWD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
          export DB_HOST=${{ secrets.DB_HOST }} DB_USER=${{ secrets.DB_USER }} DB_PSWD=${{ secrets.DB_PSWD }} DB_NAME=${{ secrets.DB_NAME }}
          sudo systemctl daemon-reload
          cd /home/ec2-user/SteganographyProject
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart app.service
          EOF
